### ISSUE TITLE
PyPI v 0.2.0 not up to date

### ISSUE THREAD

**Issue by HarryMWinters** [dbrgn/drf-dynamic-fields#22]
Hey folks. Thanks for the mixin. Definitely made my life easier. 

Unfortunately v 0.2.0 is not up to date on PyPI. Specifically the merge preventing the filter from being applied to nested serializers is not present. 

Thanks again and cheers.

**Comment by dbrgn** [comment]
Thanks for the heads-up. Version 0.3.0 is relased on PyPi.
