### ISSUE TITLE
Access to context fails inside nested serializer

### ISSUE THREAD

**Issue by jtrain** [dbrgn/drf-dynamic-fields#6]
As discussed in #5 a DynamicFieldMixin-ed serializer that accesses `context` will fail when used as a nested serializer.

I found this issue when I was re-using a serializer as a nested serializer, and that serializer relies on `context['request']` to build a url for one of its fields.

Without fixing `drf-dynamic-fields` to allow nested serializers, there are a number of work arounds:

1. You could just have two separate serializers, one for nesting and one for normal views.
2. The nested serializer can manually find the correct `context` by chasing the `parent` fields up the tree until it finds the one with `context` set.

I used 2) for a while before deciding it was better to fix the underlying issue.

**Comment by jtrain** [comment]
#8 This one has the PR now for this.

**Comment by dbrgn** [comment]
Fixed by #10 I think.
